name: "PR review norification"
description: "Notifies users when a review has been addded on a PR"
author: "Ayup Atif"
inputs:
  filePath:
    description: "Input to use"
    default: "world"
  passwordSecret:
    description: "password for email"
  usernameSecret:
    description: "username for email"
  domainSecret:
    description: "domain for email"
  keyword:
    description: "keyword for notify or not"

outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
