name: Notifier
on:
  pull_request_review:
    types: [edited, dismissed, submitted]
  
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: PR review notification
      uses: isacarvid/PR-review-notification@v1
      with:
        usernameSecret: ${{ secrets.EMAIL_USERNAME }}
        passwordSecret: ${{ secrets.EMAIL_PASSWORD }}
        domainSecret: ${{ secrets.EMAIL_DOMAIN }}
        keyword: '#notify'
