name: Notifier
on:
  push:
  
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get README.md
        run: |
          git fetch --quiet
          diffFiles=$(git diff origin/master HEAD --name-only)
          diffFiles="${diffFiles//'%'/'%25'}"
          diffFiles="${diffFiles//$'\n'/'%0A'}"
          diffFiles="${diffFiles//$'\r'/'%0D'}"
          echo "::set-output name=files::$diffFiles"
        id: get-diff
      - name: PR review notification
        uses: isacarvid/PR-review-notification@v1
        with:
          filePath: ${{ steps.get-diff.outputs.files}}
          usernameSecret: ${{ secrets.EMAIL_USERNAME }}
          passwordSecret: ${{ secrets.EMAIL_PASSWORD }}
          domainSecret: ${{ secrets.EMAIL_DOMAIN }}
          keyword: '#notify'
